### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by SkybuckFlying** [OpenXcom/OpenXcom#1356] opened 2022-03-06 06:41 UTC
During intro if I click mouse button or press a key.
Also after intro is done:

Exception thrown at 0x7717C5AF in OpenXcom.exe: Microsoft C++ exception: OpenXcom::Exception at memory location 0x0945E7F4.

**Comment by SkybuckFlying** [comment] 2022-03-06 07:12
This may be related to the sound issue...

**Comment by MeridianOXC** [comment] 2022-08-09 07:12
Yes, this could be related to audio issues. #1357 was however closed as cannot reproduce, so closing this one too.

**Closed** 2022-08-09 07:12 UTC
Labels: Cannot reproduce
