### ISSUE TITLE
Mods not picked up (Linux)

### ISSUE THREAD

**Issue by luqasz** [OpenXcom/OpenXcom#1282] opened 2020-11-06 22:30 UTC
Under Ubuntu 20.04, openxcom appimage executes but can not see any mods.
[openxcom.log](https://github.com/OpenXcom/OpenXcom/files/5503783/openxcom.log)

I have that mod.
```
lkostka@dbox ~/.local/share/openxcom # ls -l mods/TWoTS/
razem 4
drwxrwxr-x 1 lkostka lkostka  728 wrz 29 19:04 CYB_SoldierName/
drwxrwxr-x 1 lkostka lkostka  108 wrz 29 19:04 GEOGRAPH/
drwxrwxr-x 1 lkostka lkostka   30 wrz 29 19:04 Language/
drwxrwxr-x 1 lkostka lkostka 7922 wrz 29 19:04 Maps/
-rw-rw-r-- 1 lkostka lkostka  260 wrz 29 19:05 metadata.yml
drwxrwxr-x 1 lkostka lkostka  728 wrz 29 19:04 MGS_SoldierName/
drwxrwxr-x 1 lkostka lkostka  728 wrz 29 19:04 MPS_SoldierName/
drwxrwxr-x 1 lkostka lkostka  116 wrz 29 19:04 Resources/
drwxrwxr-x 1 lkostka lkostka 9374 wrz 29 19:04 Routes/
drwxrwxr-x 1 lkostka lkostka  924 wrz 29 19:04 Ruleset/
drwxrwxr-x 1 lkostka lkostka  306 wrz 29 19:04 Sound/
drwxrwxr-x 1 lkostka lkostka 4656 wrz 29 19:04 Terrain/
drwxrwxr-x 1 lkostka lkostka   36 wrz 29 19:04 Units/
```

**Comment by R1dO** [comment] 2020-11-06 22:40
TWoTS requires OXCE (see description on: https://openxcom.mod.io/the-world-of-terrifying-silence).

The appimage is OXC. That could explain why you are not seeing the mod.

If you want to play TWoTS you have to install OXCE (can be downloaded from https://openxcom.org/forum/index.php/topic,5258.0.html)

**Comment by luqasz** [comment] 2020-11-06 22:54
Thx. That explains some things. But still no luck [openxcom.log](https://github.com/OpenXcom/OpenXcom/files/5503862/openxcom.log)

**Comment by R1dO** [comment] 2020-11-06 23:17
`[06-11-2020_23-52-57]	[ERROR]	FileMap::mapExtResources(xcom1, UFO): external resources not found.`
Looks like it is missing required original datafiles. Did you copy the original datafiles to the correct place?
Under `~/.local/share/openxcom/` you want the following 2 folders (and content)
```
UFO
├── GEODATA
├── GEOGRAPH
├── MAPS
├── patch.txt
├── README.txt
├── ROUTES
├── SOUND
├── TERRAIN
├── UFOGRAPH
├── UFOINTRO
└── UNITS
```
and
```
TFTD
├── ANIMS
├── FLOP_INT
├── GEODATA
├── GEOGRAPH
├── MAPS
├── patch.txt
├── README.txt
├── ROUTES
├── SOUND
├── TERRAIN
├── UFOGRAPH
└── UNITS
```
It might be possible that TWoTs only needs the TFTD part, but i am not sure about it.

**Comment by luqasz** [comment] 2020-11-07 13:57
Mod works without original UFO contents. I've added 
```
  - active: true
    id: TWoTS
```
to modes section and now works. Weird since I don't see all options as on windows.

**Comment by MeridianOXC** [comment] 2022-08-09 09:21
Closing as solved (and cannot reproduce).

**Closed** 2022-08-09 09:21 UTC
