### ISSUE TITLE
Problems on macOS Big Sur

### ISSUE THREAD

**Issue by dopplershift** [OpenXcom/OpenXcom#1327] opened 2021-04-21 18:18 UTC
I just went to run OpenXcom again, and noticed that things are not working like they should:

* In windowed mode (full screen is fine), the graphics only occupy the lower left corner:
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/221526/115601753-6438b280-a29b-11eb-970d-508891d15b87.png">

* Sound doesn't work. Audio page in Options says "No audio hardware detected"

I'm currently running macOS 11.2.3. Previously had no problem building from source--and in fact rolling back to older git versions doesn't help, so this is definitely an issue with Big Sur.

**Comment by MeridianOXC** [comment] 2022-08-09 10:03
Closing as duplicate of #1320

**Closed** 2022-08-09 10:04 UTC
Labels: Confirmed
