### ISSUE TITLE
Spotted mind-controlled X-COM unit, the enemy number disappears after turning away

### ISSUE THREAD

**Issue by Fomka** [OpenXcom/OpenXcom#1338] opened 2021-07-07 17:19 UTC
An X-COM agent named Rodrigo Torres has spotted an enemy -- his buddy, mind-controlled by aliens. Visible enemies counter shows up. But it disappears when Rodrigo turns away. I expected the number to turn green from red, but not to disappear.

The game version is Extended 7.0 (built 2021.03.13), the mod is X-COM Files v1.8.

**Comment by Fomka** [comment] 2021-07-07 17:20
[X-COM Files Veteran Save.zip](https://github.com/OpenXcom/OpenXcom/files/6778985/X-COM.Files.Veteran.Save.zip)

**Comment by MeridianOXC** [comment] 2022-08-09 08:39
This is intended behavior.
Only units with original faction = hostile are shown using the green indicator.

**Comment by MeridianOXC** [comment] 2022-08-09 08:40
Closing as answered.

**Closed by MeridianOXC** 2022-08-09 08:40 UTC
