### ISSUE TITLE
Sound issue

### ISSUE THREAD

**Issue by SkybuckFlying** [OpenXcom/OpenXcom#1357] opened 2022-03-06 06:45 UTC
Sound stops working after game is terminated. Somehow sound driver for SDL seems screwed up, other drivers on system still work. Somehow goldwave still works.

Currently music can work via gm but sound won't play.

Breaking into code seems to stop here:

void FlcPlayer::deInitAudio()
{
	if (_game)
	{
		if (!Options::mute)
		{
			Mix_HookMusic(NULL, NULL);
			Mix_CloseAudio();
			_game->initAudio();   // <-
		}
	}

Kinda strange.

Long time since I used vs2019 but that is what it shows... also strange how it uses flac player default instead of adlib or midi/gm.

All I did was copy ufo files to the ufo folder... should it not use adlib by default ?

Perhaps the bug is that it's using the wrong player to de-init the sound system ?

This laptop is a bit shady/broken 3d chip etc... other apps are behaving a bit strange as well... like firefox crashing probably because sound driver is block, some media files in firefox don't play.

Restarting the system might fix it, but this is not a good solution and openXcom should be fixed so it does not cause this issue. It's a rare issue but I have seen other games cause this problem as well, like quake re-mastered or something.

I will restart the system just once to see if the issue remains... it might have been caused by switching/playing around with different audio options.

I also tried changing graphics settings to work around 3d laptop issue/screen issues.

When it's full screen strange pixels can be seen, but fortunately borderless big resolution renders ok.

Always nice if applications/games have multiple rendering options available. I am slightly surprised this game is working... but I had a feeling it might, since it's just a pixel game :) Though I do see some opengl but thankfully it can be disabled and seems to be disabled by default or auto detection ?

Anyway a job well done... code is beautifully written... my complements there too ! ;)

**Comment by SkybuckFlying** [comment] 2022-03-06 07:12
Sound issue went away after restart. For now I believe this issue may have been caused by using flac player as default. I highly recommend changing this to adlib if possible ;)

(I also did not install any openxcom patches, just ms-dos ufo 1.4 version was used, now I go try some mods =D)

**Comment by SkybuckFlying** [comment] 2022-03-06 07:19
The flac player sounds awesome though ! I just tried it. Now I am not so sure anymore what caused the problem.

Maybe a crash because of video options changed, or maybe game hang of video corruption... could still be an audio problem... just not sure... will check in future... though the sound issue can be real... seen it before... but then it usually takes out the entire audio stack, this time it was only partially...

right now it's working, but can't get the mod working from piratez it doesn't show up yet, but I ll read how to install mods, extracted it to mod folder but apperently not enough.. not in list ohwell i am excited =D

**Comment by MeridianOXC** [comment] 2022-08-09 07:10
Closing as cannot reproduce.

**Closed** 2022-08-09 07:10 UTC
Labels: Cannot reproduce
